com:
  hideyoshi:
    frontendPath: ${FRONTEND_PATH}
    frontendConnectionType: ${FRONTEND_CONNECTION_TYPE}
    tokenSecret: ${TOKEN_SECRET}
    accessTokenDuration: ${ACCESS_TOKEN_DURATION}
    refreshTokenDuration: ${REFRESH_TOKEN_DURATION}
    defaultUser:
      fullName: ${DEFAULT_USER_FULLNAME}
      email: ${DEFAULT_USER_EMAIL}
      username: ${DEFAULT_USER_USERNAME}
      password: ${DEFAULT_USER_PASSWORD}


server:
  servlet:
    session:
      cookie:
        same-site: none
  port: ${PORT}

spring:

  security:
    oauth2:
      client:
        registration:

          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: ${GOOGLE_REDIRECT_URL}
            scope:
              - email
              - profile

          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            redirectUri: ${GITHUB_REDIRECT_URL}
            scope:
              - user

  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  session:
    store:
      type: redis
      persistent: true

  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
