
services:
    postgres:
        image: postgres:14.13
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: portfolio
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        image: bitnami/redis
        container_name: redis
        environment:
            REDIS_PASSWORD: redis
        ports:
            - "6379:6379"
        volumes:
            - redis:/data

volumes:
    postgres:
    redis: